#TODO: better anotate these in the futrue
# cursor detailes
env = XCURSOR_SIZE,14
env = HYPRCURSOR_SIZE,14

# nvidia 
debug:full_cm_proto = true
env = NVD_BACKEND,direct
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = LIBVA_DRIVER_NAME,nvidia
# force apps to use wayland by default
env = GDK_BACKEND,wayland,x11,*
env = GDK_SCALE,1.25
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_STYLE_OVERRIDE,kvantum
env = QT_QUICK_CONTROLS_STYLE,org.kde.desktop
env = QT_QPA_PLATFORM,wayland;xcb
env = MOZ_ENABLE_WAYLAND,1
env = ELECTRON_OZONE_PLATFORM_HINT,wayland
env = OZONE_PLATFORM,wayland
env = XDG_SESSION_TYPE,wayland
env = XDG_MENU_PREFIX,arch-
# for better screen sharing 
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland
