dwindle {
    # pseudotile = true
    preserve_split = true
}

master {
    new_status = slave
    smart_resizing = true
    mfact = 0.75
}

scrolling {
  column_width = 0.75
}


workspace = 4 , layout:scrolling

