# background tasks
exec-once = hyprpanel
exec-once = nm-applet --indicator
exec-once = hyprpaper
exec-once = ~/.config/hypr/scripts/switch_wallpaper.sh
exec-once = hypridle #idle app to lock the screen
exec-once = kbuildsycoca6
exec-once = $polkit
exec-once = /home/coshi/Work/my_scripts/data_place.sh
exec-once = /usr/lib/pam_kwallet_init
exec-once = dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY
exec-once = kwalletd6 &
# applications
exec-once = [workspace 1 silent] $terminal
exec-once = [workspace 5 silent] $fileManager
exec-once = [workspace 2 silent] $browser
exec-once = [workspace 3 silent] $chatApp
exec-once = syncthing
