# programe launch commands
$terminal = ghostty
$fileManager = dolphin
$menu = rofi -show drun
$window = rofi -show window
$emoji = rofi -modi emoji -show emoji 
$browser = zen-browser
$chatApp = vesktop
$polkit = /usr/lib/hyprpolkitagent/hyprpolkitagent
$calculator = flatpak run io.github.Qalculate.qalculate-qt
$clock = kclock

# action commands
$monitor_shot = hyprshot -m output -m eDP-1 --raw | swappy -f - 
$region_shot =  hyprshot -m region --raw | swappy -f -

# key combinations
$mainMod = SUPER # Sets "Windows" key as main modifier
