# suppress_event (with underscore), effect value 'maximize', and match:class
windowrule = suppress_event maximize, match:class .*

# Fix dragging issues with XWayland
# no_focus (with underscore), effect value 'on', 
# and explicit match: prefixes for all window properties.
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0

# make all games (at least with gamescope) full screen
windowrule = match:class gamescope , fullscreen on
windowrule = match:class mpv , fullscreen on

# Workspace Assignments
windowrule = match:class .* , workspace 4 # by default open windows in the 4th workspace 

windowrule = match:class com.mitchellh.ghostty, workspace 1 
windowrule = match:title gf2 ,  workspace 1

windowrule = match:class zen, workspace 2 

windowrule = match:class WhatsApp Desktop, workspace 3
windowrule = match:class vesktop, workspace 3  
windowrule = match:class org.telegram.desktop, workspace 3  

windowrule = match:class org.kde.dolphin , workspace 5 

# stay in the active workspace
windowrule = match:class io.github.Qalculate.qalculate-qt , workspace e
windowrule = match:class org.kde.kweather , workspace e
windowrule = match:class org.kde.kclock , workspace e
windowrule = match:class org.freedesktop.impl.portal.desktop.kde , workspace e
windowrule = match:class swappy , workspace e
