source=~/.config/hypr/conf_files/variables.conf
source=~/.config/hypr/conf_files/monitor.conf
source=~/.config/hypr/conf_files/look.conf
source=~/.config/hypr/conf_files/animation.conf
source=~/.config/hypr/conf_files/layout.conf
source=~/.config/hypr/conf_files/startup.conf
source=~/.config/hypr/conf_files/env.conf
source=~/.config/hypr/conf_files/input.conf
source=~/.config/hypr/conf_files/keybinds.conf
source=~/.config/hypr/conf_files/windowrules.conf
